# Generated by Django 2.2.1 on 2019-05-28 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190528_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Comment'),
        ),
    ]
